# Generated by Django 4.2.5 on 2024-12-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chat",
            new_name="Message",
        ),
    ]
